import Head from 'next/head'
import type { NextPage } from 'next'
import Header from '../components/Header'
import HeaderSection from '../components/HeaderSection'

import Features from '../components/Features'
import Categories from '../components/Categories'
import BestSellers from '../components/BestSellers'
import Testimonial from '../components/Testimonial'

import Newsletter from '../components/Newsletter'
import Footer from '../components/Footer'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Plant shop figma to tailwind css with nextjs !</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='w-[1600px] bg-[#FFFFFF] mx-auto h-screen overflow-y-scroll scrollbar-none flex relative'>
        <div className='w-full mx-[120px] mt-[40px] z-10'>
          {/* header section */}
          <Header />
          <HeaderSection />
          {/* body */}
          <Features />
          <Categories />
          <BestSellers />
          <Testimonial />
          {/* footer */}
          <Newsletter />
          <Footer />
        </div>
        <div className='bg-secondaryLightGreen w-[1106px] h-[933px] absolute top-0 left-0 z-0' />
      </main>
    </>
  )
}

export default Home
